package com.megamall.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF6750A4)
val md_theme_light_on_primary = Color(0xFFFFFFFF)
val md_theme_light_primary_container = Color(0xFFEADDFF)
val md_theme_light_on_primary_container = Color(0xFF21005E)
val md_theme_light_secondary = Color(0xFF625B71)
val md_theme_light_on_secondary = Color(0xFFFFFFFF)
val md_theme_light_secondary_container = Color(0xFFE8DEF8)
val md_theme_light_on_secondary_container = Color(0xFF1E192B)
val md_theme_light_tertiary = Color(0xFF7D5260)
val md_theme_light_on_tertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiary_container = Color(0xFFFFD8E4)
val md_theme_light_on_tertiary_container = Color(0xFF31111D)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_on_error = Color(0xFFFFFFFF)
val md_theme_light_error_container = Color(0xFFF9DEDC)
val md_theme_light_on_error_container = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_on_background = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_on_surface = Color(0xFF1C1B1F)
val md_theme_light_surface_variant = Color(0xFFE7E0EC)
val md_theme_light_on_surface_variant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_outline_variant = Color(0xFFCAC7D0)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_inverse_surface = Color(0xFF313033)
val md_theme_light_inverse_on_surface = Color(0xFFF4EFF4)
val md_theme_light_inverse_primary = Color(0xFFD0BCFF)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFD0BCFF)
val md_theme_dark_on_primary = Color(0xFF371E55)
val md_theme_dark_primary_container = Color(0xFF4F378B)
val md_theme_dark_on_primary_container = Color(0xFFEADDFF)
val md_theme_dark_secondary = Color(0xFFCCC7DB)
val md_theme_dark_on_secondary = Color(0xFF332D41)
val md_theme_dark_secondary_container = Color(0xFF4A4458)
val md_theme_dark_on_secondary_container = Color(0xFFE8DEF8)
val md_theme_dark_tertiary = Color(0xFFF4B8C5)
val md_theme_dark_on_tertiary = Color(0xFF492532)
val md_theme_dark_tertiary_container = Color(0xFF633B48)
val md_theme_dark_on_tertiary_container = Color(0xFFFFD8E4)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_on_error = Color(0xFF601410)
val md_theme_dark_error_container = Color(0xFF8C1D18)
val md_theme_dark_on_error_container = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_on_background = Color(0xFFE6E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_on_surface = Color(0xFFE6E1E6)
val md_theme_dark_surface_variant = Color(0xFF49454E)
val md_theme_dark_on_surface_variant = Color(0xFFCAC7D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_outline_variant = Color(0xFF49454E)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_inverse_surface = Color(0xFFE6E1E6)
val md_theme_dark_inverse_on_surface = Color(0xFF313033)
val md_theme_dark_inverse_primary = Color(0xFF6750A4)

// Status Colors
val success = Color(0xFF4CAF50)
val warning = Color(0xFFFF9800)
val error = Color(0xFFF44336)
val info = Color(0xFF2196F3)
