name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'


    - name: Setup Android SDK
      uses: android-actions/setup-android@v3


    - name: Install Android SDK
      run: |
        yes | sdkmanager --licenses || true

        sdkmanager \
        "platform-tools" \
        "platforms;android-29" \
        "build-tools;29.0.3"


    - name: Fix Gradle wrapper
      run: |
        sed -i \
        's#^distributionUrl=.*#distributionUrl=https://services.gradle.org/distributions/gradle-5.4.1-all.zip#' \
        gradle/wrapper/gradle-wrapper.properties


    - name: Prepare Gradle
      run: |
        chmod +x gradlew

        echo "JAVA_HOME=$JAVA_HOME"

        export JAVA_HOME=$JAVA_HOME

        java -version


    - name: Remove Firebase plugin if missing
      run: |
        if [ ! -f app/google-services.json ]; then
          sed -i "/apply plugin: 'com.google.gms.google-services'/d" app/build.gradle
        fi


    - name: Build APK
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        chmod +x ./gradlew

        ./gradlew assembleDebug \
        --no-daemon \
        --stacktrace


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
